#!/bin/bash
echo "Hello from run_container"

# start redis-server
redis-server --protected-mode no


finish() {
    rm tmpfiles
    exit
}

trap finish SIGINT

while :; do
    echo "Running..."
    sleep 3
done
