#!/bin/bash
echo "Hello from run_container"

# start redis-server
echo 'Starting redis-server...'
nohup redis-server --protected-mode no > /dev/null 2>&1 &
echo "Redis started."

echo "Starting Eventron..."
nohup node Eventron > /dev/null 2>&1 &
nohup node Eventron/index.js > /dev/null 2>&1 &
echo "Eventron started."

finish() {
    rm tmpfiles
    exit
}

trap finish SIGINT

while :; do
    echo "Running..."
    sleep 3
done
